// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmFqXRp8bSzNYIkk4eO0rPLYLUoDVs3ig',
    appId: '1:601776580207:web:d365530af3aa823db10f9a',
    messagingSenderId: '601776580207',
    projectId: 'flutterrole',
    authDomain: 'flutterrole.firebaseapp.com',
    storageBucket: 'flutterrole.appspot.com',
    measurementId: 'G-LRQ497Q2G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5RW9ED5UjMZhN4x8Gmn3YcQX4Mq_7sQ',
    appId: '1:601776580207:android:26f69ef20ee66266b10f9a',
    messagingSenderId: '601776580207',
    projectId: 'flutterrole',
    storageBucket: 'flutterrole.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrkQ2rvmHcogm7aF0K-UEHLzceWI4V6o',
    appId: '1:601776580207:ios:b5dd585f76c52e9eb10f9a',
    messagingSenderId: '601776580207',
    projectId: 'flutterrole',
    storageBucket: 'flutterrole.appspot.com',
    iosBundleId: 'com.example.flutterrole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhrkQ2rvmHcogm7aF0K-UEHLzceWI4V6o',
    appId: '1:601776580207:ios:dd183bf416834d77b10f9a',
    messagingSenderId: '601776580207',
    projectId: 'flutterrole',
    storageBucket: 'flutterrole.appspot.com',
    iosBundleId: 'com.example.flutterrole.RunnerTests',
  );
}
